name: Build SM64 PS3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3 python3-pip
      - name: Setup SDK
        run: |
          wget https://github.com
          # Nota: O repositório do Sdiraimondo costuma aceitar o compilador GCC padrão se configurado.
      - name: Build
        run: |
          cp bin/baserom.us.z64 ./baserom.us.z64
          make
      - name: Upload PKG
        uses: actions/upload-artifact@v4
        with:
          name: sm64-ps3-pkg
          path: |
            ./*.pkg
            ./build/ps3/*.pkg
