name: Build SM64 PS3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Base Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3 wget libelf-dev vbindiff
          
      - name: Install PS3 SDK
        run: |
          wget https://github.com -O ps3dev.tar.gz
          sudo tar -xzvf ps3dev.tar.gz -C /
          echo "PS3DEV=/usr/local/ps3dev" >> $GITHUB_ENV
          echo "PSL1GHT=/usr/local/ps3dev/psl1ght" >> $GITHUB_ENV
          echo "/usr/local/ps3dev/bin" >> $GITHUB_PATH
          echo "/usr/local/ps3dev/ppu/bin" >> $GITHUB_PATH

      - name: Build SM64 PKG
        run: |
          cp bin/baserom.us.z64 ./baserom.us.z64
          make COMPARE=0 -j$(nproc)
          
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: sm64-ps3-pkg
          path: |
            ./*.pkg
            ./build/ps3/*.pkg

